name: Crome - Ubuntu RDP
on: 
  workflow_dispatch:
    inputs:
      code:
        description: 'Chrome Remote Desktop Code | Debian Linux'
        required: true
      pin:
        description: '6 digits PIN'
        required: true
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Create User
      run: sudo useradd -m CRDUser1 && sudo adduser CRDUser1 sudo && echo 'CRDUser1:CRDUser1' | sudo chpasswd
    - name: Doanload & Install files
      run: | 
        echo Update: APT
        sudo apt update
        echo Install: Ubuntu Desktop
        sudo apt install ubuntu-desktop
        echo Download: Chrome
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        echo Install: Chrome
        sudo dpkg --install google-chrome-stable_current_amd64.deb
        sudo apt install --assume-yes --fix-broken
        echo Install: Xbase Clients
        sudo apt-get install xbase-clients python3-psutil xvfb -y
        echo Install: Chrome Remote Desktop
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo dpkg --install chrome-remote-desktop_current_amd64.deb
        sudo apt install --assume-yes --fix-broken
        echo Download: Keep Alive
        wget https://raw.githubusercontent.com/PRO-E5/RDP-E1/RDP/loop.sh
    - name: Start Chrome Remote Desktop
      run: ${{ github.event.inputs.code }} -pin=${{ github.event.inputs.pin }}
    - name: Done! You can see the machine in list now.
      run: bash loop.sh
